# http://localhost:8080/actuator/gateway/routes
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: userms
          uri: lb://CARTMS
          predicates:
            - Path=/ordersms/**
          filters:
            - RewritePath=/ordersms/(?<path>.*), /$\{path}
        - id: customerms
          uri: lb://CUSTOMERMS
          predicates:
            - Path=/customerms/**
          filters:
            - RewritePath=/customerms/(?<path>.*), /$\{path}
        - id: productms
          uri: lb://PRODUCTMS
          predicates:
            - Path=/productms/**
          filters:
            - RewritePath=/productms/(?<path>.*), /$\{path}
      default-filters:
        - name: VailidateTokenFilter

# http://localhost:8080/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: '*'